
import 'dart:convert';

String albumToJson(List<User> data) =>
    json.encode(List<dynamic>.from(data.map((x) => x.toJson())));

class Autogenerated {
  List<User> info;
  String message;
  int status;

  Autogenerated({this.info, this.message, this.status});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['info'] != null) {
      info = new List<User>();
      json['info'].forEach((v) {
        info.add(new User.fromJson(v));
      });
    }
    message = json['message'];
    status = json['status'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.info != null) {
      data['info'] = this.info.map((v) => v.toJson()).toList();
    }
    data['message'] = this.message;
    data['status'] = this.status;
    return data;
  }
}

class User {
  int orderId;
  int driverId;
  int orderStatus;
  int userId;
  int addressId;
  Null notes;
  int businessId;
  String acceptedByBusiness;
  String pickupTime;
  String deliveryTime;
  String totalPayableAmount;
  Null sizeId;
  int totalDiscount;
  String orderTime;
  String itemTotalAmount;
  String deliveryFees;
  String createdAt;
  int itemCount;
  String businessName;
  Null businessAddress;
  String profilePic;

  User(
      {this.orderId,
        this.driverId,
        this.orderStatus,
        this.userId,
        this.addressId,
        this.notes,
        this.businessId,
        this.acceptedByBusiness,
        this.pickupTime,
        this.deliveryTime,
        this.totalPayableAmount,
        this.sizeId,
        this.totalDiscount,
        this.orderTime,
        this.itemTotalAmount,
        this.deliveryFees,
        this.createdAt,
        this.itemCount,
        this.businessName,
        this.businessAddress,
        this.profilePic});

  User.fromJson(Map<String, dynamic> json) {
    orderId = json['order_id'];
    driverId = json['driver_id'];
    orderStatus = json['order_status'];
    userId = json['user_id'];
    addressId = json['address_id'];
    notes = json['notes'];
    businessId = json['business_id'];
    acceptedByBusiness = json['accepted_by_business'];
    pickupTime = json['pickup_time'];
    deliveryTime = json['delivery_time'];
    totalPayableAmount = json['total_payable_amount'];
    sizeId = json['size_id'];
    totalDiscount = json['total_discount'];
    orderTime = json['order_time'];
    itemTotalAmount = json['item_total_amount'];
    deliveryFees = json['delivery_fees'];
    createdAt = json['created_at'];
    itemCount = json['item_count'];
    businessName = json['business_name'];
    businessAddress = json['business_address'];
    profilePic = json['profile_pic'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['order_id'] = this.orderId;
    data['driver_id'] = this.driverId;
    data['order_status'] = this.orderStatus;
    data['user_id'] = this.userId;
    data['address_id'] = this.addressId;
    data['notes'] = this.notes;
    data['business_id'] = this.businessId;
    data['accepted_by_business'] = this.acceptedByBusiness;
    data['pickup_time'] = this.pickupTime;
    data['delivery_time'] = this.deliveryTime;
    data['total_payable_amount'] = this.totalPayableAmount;
    data['size_id'] = this.sizeId;
    data['total_discount'] = this.totalDiscount;
    data['order_time'] = this.orderTime;
    data['item_total_amount'] = this.itemTotalAmount;
    data['delivery_fees'] = this.deliveryFees;
    data['created_at'] = this.createdAt;
    data['item_count'] = this.itemCount;
    data['business_name'] = this.businessName;
    data['business_address'] = this.businessAddress;
    data['profile_pic'] = this.profilePic;
    return data;
  }
}
