import 'dart:convert';
import 'dart:io';
import '../data/userData.dart';
import 'package:http/http.dart' as http;
import 'package:http/http.dart';

abstract class UsersRepo {
  Future<List<User>> getUserList();
}

class AlbumServices implements UsersRepo {
  //
  static const _baseUrl = 'http://206.189.68.189:4000/list_order_by_status';
  static const String _tokens = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImlhdCI6MTYwOTE1NDkwM30.GKEJ1yiZVZvrKRrXrY1hFKTLFZdUjt410mhwsxXN06s';

  @override
  Future<List<User>> getUserList() async {
    Response response = await http.post(_baseUrl,
        body: {"order_status": '0'},
        headers: {HttpHeaders.authorizationHeader: 'Bearer' + ' ' + _tokens});
    print(response.body);
    var data= await jsonDecode(response.body);
    List<User> articles = Autogenerated.fromJson(data).info;
    return articles;
/*    List<User> albums = ;
    return albums;*/

  }
}
